# Generated by Django 6.0.5 on 2026-05-15 09:05

import lotto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='numbers',
        ),
        migrations.AddField(
            model_name='draw',
            name='first_numbers',
            field=models.CharField(default=lotto.models.generate_numbers, max_length=50),
        ),
        migrations.AddField(
            model_name='draw',
            name='second_numbers',
            field=models.CharField(default=lotto.models.generate_numbers, max_length=50),
        ),
        migrations.AddField(
            model_name='draw',
            name='third_numbers',
            field=models.CharField(default=lotto.models.generate_numbers, max_length=50),
        ),
    ]
