# Generated by Django 6.0.5 on 2026-05-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_remove_draw_numbers_draw_first_numbers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draw',
            old_name='first_numbers',
            new_name='winning_numbers',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='second_numbers',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='third_numbers',
        ),
    ]
